name: Set Repo Secrets
on:
  workflow_dispatch:
    inputs:
      repoOwner:
        description: 'Owner of the repo'
        required: true
      repoName:
        description: 'Name of the repo'
        required: true
      group:
        type: choice
        description: 'Group of secrets to get values from'
        required: true
        options: ['personal', 'internal']
        default: 'personal'

jobs:
  set-personal-secrets:
    if: ${{ github.event.inputs.group == 'personal' }}
    env:
      AZURE_AD_CLIENT_ID: ${{ secrets.PERSONAL_AZURE_AD_CLIENT_ID }}
      AZURE_AD_CLIENT_SECRET: ${{ secrets.PERSONAL_AZURE_AD_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.PERSONAL_AZURE_SUBSCRIPTION_ID }}
      AZURE_AD_TENANT_ID: ${{ secrets.PERSONAL_AZURE_AD_TENANT_ID }}
      AZURE_CREDENTIALS: ${{ secrets.PERSONAL_AZURE_CREDENTIALS }}
      TF_BACKEND_STORAGE_ACCOUNT: ${{ vars.PERSONAL_TF_BACKEND_STORAGE_ACCOUNT }}
      TF_BACKEND_STORAGE_CONTAINER: ${{ vars.PERSONAL_TF_BACKEND_STORAGE_CONTAINER }}
      TF_BACKEND_STORAGE_RESOURCE_GROUP: ${{ vars.PERSONAL_TF_BACKEND_STORAGE_RESOURCE_GROUP }}
      TF_BACKEND_STORAGE_KEY: '${{ github.event.inputs.repoName }}.tfstate'
    runs-on: ubuntu-latest
    steps:
      - name: Set Repo Secrets
        uses: howlowck/set-secrets-action@main
        with:
          repo-owner: ${{ github.event.inputs.repoOwner }}
          repo-name: ${{ github.event.inputs.repoName }}
          security-token: ${{ secrets.SECURITY_TOKEN }}
          secrets-from-env: |-
            AZURE_AD_CLIENT_ID=AZURE_AD_CLIENT_ID
            AZURE_AD_CLIENT_SECRET=AZURE_AD_CLIENT_SECRET
            AZURE_SUBSCRIPTION_ID=AZURE_SUBSCRIPTION_ID
            AZURE_AD_TENANT_ID=AZURE_AD_TENANT_ID
            AZURE_CREDENTIALS=AZURE_CREDENTIALS
          vars-from-env: |-
            TF_BACKEND_STORAGE_ACCOUNT=TF_BACKEND_STORAGE_ACCOUNT
            TF_BACKEND_STORAGE_CONTAINER=TF_BACKEND_STORAGE_CONTAINER
            TF_BACKEND_STORAGE_RESOURCE_GROUP=TF_BACKEND_STORAGE_RESOURCE_GROUP
            TF_BACKEND_STORAGE_KEY=TF_BACKEND_STORAGE_KEY